(()=>{'use strict';const $=id=>document.getElementById(id),clock=document.querySelector('.clock-card'),gps=document.querySelector('.speed-card');let ready=false,user=null,csrf='',pending=Promise.resolve(),weatherSeq=0,prefs={clock:'aurora',gps:'ring',side:'right',city:'tokyo',theme:'original'};
const cities={tokyo:[35.68,139.69,'Tokyo'],hanoi:[21.03,105.85,'Hà Nội'],hcm:[10.82,106.63,'TP. Hồ Chí Minh'],berlin:[52.52,13.4,'Berlin']};
async function api(path,data){const r=await fetch(path,{cache:'no-store',credentials:'same-origin',...(data?{method:'POST',headers:{'Content-Type':'application/json','X-CSRF-Token':csrf},body:JSON.stringify(data)}:{})});const v=await r.json();if(!r.ok||!v.ok)throw Error(v.error||'Chưa kết nối được máy chủ.');return v;}
function options(){ $('optionsSheet').hidden=false;$('closeOptions').focus(); }
$('optionsBtn').onclick=options;$('closeOptions').onclick=()=>{$('optionsSheet').hidden=true;($('appsTab')||$('optionsBtn')).focus();};document.addEventListener('keydown',e=>{if(e.key==='Escape')$('closeOptions').click();});
function pro(){if(!ready){$('optionsStatus').textContent='Đang tải tùy chọn tài khoản…';options();return false;}if(user?.pro)return true;$('optionsStatus').textContent='Đổi mẫu giao diện và đổi bên thuộc Pro. Liên hệ quản trị viên để kích hoạt Pro.';options();return false;}
function apply(){document.body.dataset.theme=prefs.theme;$('themeSelect').value=prefs.theme;clock.dataset.clockPreset=prefs.clock;gps.dataset.gpsPreset=prefs.gps;clock.dataset.clock='aurora';gps.dataset.gps='ring';document.body.classList.toggle('widgets-left',prefs.side==='left');$('clockStyleLabel').textContent={aurora:'AURORA',digital:'FUJI SAPPHIRE',classic:'FUJI ROSE',jade:'FUJI JADE',silver:'FUJI SILVER',sakura:'SAKURA',skytree:'TOKYO SKYTREE',disney:'TOKYO DISNEY'}[prefs.clock];$('gpsStyleLabel').textContent={ring:'CHUYẾN ĐI · GPS',sport:'SAPPHIRE · GPS',minimal:'ROSE · GPS',jade:'JADE · GPS',silver:'SILVER · GPS'}[prefs.gps];$('sideBtn').textContent='Chuyển tiện ích sang '+(prefs.side==='left'?'phải':'trái')+(user?.pro?'':' · Pro');$('swapSideBtn').textContent='⇄';$('swapSideBtn').setAttribute('aria-label','Chuyển đồng hồ và GPS sang '+(prefs.side==='left'?'phải':'trái'));if(!window.VeloraLocation?.sync())$('weatherCity').value=prefs.city;window.dispatchEvent(new Event('resize'));}
window.VeloraExperience={selectClock:value=>{if(!pro())return;if(!['aurora','digital','classic','jade','silver','sakura','skytree','disney'].includes(value))return;prefs.clock=value;apply();save();},profile:p=>{if(!user?.pro)return;const changed=prefs.theme!==p.theme||prefs.side!==p.side;prefs.theme=p.theme;prefs.side=p.side;apply();if(changed)save();}};
function garageSync(){const g=window.VeloraGarage;if(g?.pro&&g.configured){const d=g.copy();d.profiles[d.active].theme=prefs.theme;d.profiles[d.active].side=prefs.side;g.save(d).catch(e=>{$('optionsStatus').textContent=e.message;});}}
function save(){const data={...prefs};pending=pending.catch(()=>{}).then(()=>api('api/preferences.php',data)).then(()=>{$('optionsStatus').textContent='Đã lưu tùy chọn vào tài khoản.';}).catch(e=>{$('optionsStatus').textContent=e.message;});}
function cycle(kind,dir=1){if(!pro())return;const values=kind==='clock'?['aurora','digital','classic','jade','silver','sakura','skytree','disney']:['ring','sport','minimal','jade','silver'];prefs[kind]=values[(values.indexOf(prefs[kind])+dir+values.length)%values.length];apply();save();}
$('clockNext').onclick=()=>cycle('clock');$('gpsNext').onclick=()=>cycle('gps');
for(const [element,kind] of [[clock,'clock'],[gps,'gps']]){let start=null;element.addEventListener('pointerdown',e=>{if(e.target.closest('button,a,input,select'))return;start={id:e.pointerId,x:e.clientX,y:e.clientY};});element.addEventListener('pointerup',e=>{if(!start||start.id!==e.pointerId)return;const dx=e.clientX-start.x,dy=e.clientY-start.y;start=null;if(Math.abs(dx)>55&&Math.abs(dx)>Math.abs(dy)*1.5)cycle(kind,dx<0?1:-1);});element.addEventListener('pointercancel',()=>start=null);}
$('swapSideBtn').onclick=()=>{$('sideBtn').click();};
$('sideBtn').onclick=()=>{if(!pro())return;prefs.side=prefs.side==='left'?'right':'left';apply();save();garageSync();};
$('themeSelect').onchange=()=>{if(!pro()){apply();return;}prefs.theme=$('themeSelect').value;apply();save();garageSync();};
$('weatherCity').onchange=()=>{if($('weatherCity').value==='gps'){window.VeloraLocation?.request();return;}window.VeloraLocation?.preset();prefs.city=$('weatherCity').value;try{localStorage.setItem('veloraWeatherCity',prefs.city);}catch(_){}if(user?.pro)save();weather();};
function condition(code){if(code===0)return '☀ Trời quang';if(code<=3)return '☁ Có mây';if(code<=48)return 'Sương mù';if(code>=95)return '⛈ Dông';if((code>=71&&code<=77)||(code>=85&&code<=86))return '❄ Tuyết';return '☂ Mưa';}
function weather(position){return window.VeloraWeather.update(position||cities[prefs.city]);}
$('weatherBtn').onclick=()=>window.VeloraWeather.update();$('weatherLocation').onclick=()=>window.VeloraLocation?.request();
let first=true;async function refresh(){try{const s=await api('api/account.php');const wasPro=!!user?.pro;user=s.user;csrf=s.csrf;$('planStatus').textContent=user?(user.pro?'Pro · ':'Free · ')+'Thiết bị đã kích hoạt':'Free · Chưa kích hoạt';if(user?.pro&&(first||!wasPro)){const r=await api('api/preferences.php');for(const k of Object.keys(prefs)){const allowed={clock:['aurora','digital','classic','jade','silver','sakura','skytree','disney'],gps:['ring','sport','minimal','jade','silver'],side:['right','left'],city:Object.keys(cities),theme:['original','kitty','sakura','ocean','night','amber','titanium','obsidian','champagne','sapphire']}[k];if(allowed.includes(r.preferences[k]))prefs[k]=r.preferences[k];}}if(!user?.pro){prefs={clock:'aurora',gps:'ring',side:'right',city:prefs.city,theme:'original'};}const g=window.VeloraGarage;if(user?.pro&&g?.configured){const p=g.data.profiles[g.data.active];prefs.theme=p.theme;prefs.side=p.side;}first=false;ready=true;apply();$('swapSideBtn').disabled=false;window.dispatchEvent(new CustomEvent('velora-account',{detail:{user,csrf}}));}catch(_){user=null;ready=false;prefs.clock='aurora';prefs.gps='ring';prefs.side='right';prefs.theme='original';apply();window.dispatchEvent(new CustomEvent('velora-account',{detail:{user:null,csrf:''}}));$('planStatus').textContent='Chưa kết nối được tài khoản · đang dùng tiện ích cơ bản';}}
try{const c=localStorage.getItem('veloraWeatherCity');if(cities[c])prefs.city=c;}catch(_){}apply();refresh().finally(()=>window.VeloraWeather.start(cities[prefs.city]));setInterval(()=>{if(!document.hidden)refresh();},60000);
})();
