(()=>{'use strict';const auto=document.currentScript?.dataset.auto==='true';const key='velora-esim-session-seen';let modal=null,previous=null;
function close(){if(!modal)return;modal.remove();modal=null;document.body.classList.remove('promotion-open');previous?.focus();}
function show(data){if(modal||!data?.title)return;previous=document.activeElement;modal=document.createElement('div');modal.className='promotion-overlay';modal.setAttribute('role','dialog');modal.setAttribute('aria-modal','true');modal.setAttribute('aria-labelledby','promotionTitle');
 const shell=document.createElement('section');shell.className='promotion-dialog';const head=document.createElement('header'),tag=document.createElement('span'),x=document.createElement('button');tag.textContent='ƯU ĐÃI eSIM · QUẢNG CÁO';x.type='button';x.className='promotion-close';x.setAttribute('aria-label','Đóng quảng cáo');x.textContent='✕';x.onclick=close;const zoom=document.createElement('button');zoom.type='button';zoom.className='promotion-zoom';zoom.textContent='Phóng to ảnh';zoom.hidden=!data.imageUrl;head.append(tag,zoom,x);
 const body=document.createElement('div');body.className='promotion-body';if(data.imageUrl){const img=document.createElement('img');img.className='promotion-image';img.src=data.imageUrl;img.alt='Ưu đãi eSIM';img.onerror=()=>{img.remove();zoom.hidden=true;body.classList.remove('image-expanded');body.classList.add('no-image');};img.onclick=()=>zoom.click();body.append(img);}else body.classList.add('no-image');const text=document.createElement('div');text.className='promotion-copy';const title=document.createElement('h2');title.id='promotionTitle';title.textContent=data.title;const p=document.createElement('p');p.textContent=data.body||'';text.append(title,p);
 if(data.url){try{const url=new URL(data.url);if(url.protocol==='https:'&&!url.username&&!url.password){const a=document.createElement('a');a.href=url.href;a.className='promotion-buy';a.textContent=data.label||'Xem ưu đãi';a.rel='noopener';text.append(a);}}catch(_){}}
 zoom.onclick=()=>{const enlarged=body.classList.toggle('image-expanded');zoom.textContent=enlarged?'Ảnh + nội dung':'Phóng to ảnh';zoom.setAttribute('aria-pressed',String(enlarged));};body.append(text);shell.append(head,body);modal.append(shell);modal.addEventListener('click',e=>{if(e.target===modal)close();});modal.addEventListener('keydown',e=>{if(e.key==='Escape'){e.preventDefault();close();}if(e.key==='Tab'){const all=[...modal.querySelectorAll('button,a[href]')];const first=all[0],last=all.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}});document.body.append(modal);document.body.classList.add('promotion-open');x.focus();}
window.VeloraPromotion={show,close};
function seen(){try{if(sessionStorage.getItem(key))return true;}catch(_){}return document.cookie.split(';').some(v=>v.trim().startsWith(key+'=1'));}
function mark(){try{sessionStorage.setItem(key,'1');return;}catch(_){}document.cookie=key+'=1; Path=/; SameSite=Lax'+(location.protocol==='https:'?'; Secure':'');}
if(auto&&!seen())fetch('api/promotion.php',{cache:'no-store',credentials:'same-origin'}).then(r=>r.ok?r.json():null).then(v=>{const ad=v?.promotion;if(!ad?.enabled||!ad.title||seen())return;mark();show({...ad,imageUrl:ad.hasImage?'api/promotion.php?image='+encodeURIComponent(ad.version):null});}).catch(()=>{});
})();
